package day9

import (
	"aoc2022/pkg/util"
	"bufio"
	"strconv"
	"strings"
)

/*
--- Day 9: Rope Bridge ---

This rope bridge creaks as you walk along it. You aren't sure how old it is, or whether it can even support your weight.
It seems to support the Elves just fine, though. The bridge spans a gorge which was carved out by the massive river far
below you. You step carefully; as you do, the ropes stretch and twist. You decide to distract yourself by modeling rope
physics; maybe you can even figure out where not to step. Consider a rope with a knot at each end; these knots mark the
head and the tail of the rope. If the head moves far enough away from the tail, the tail is pulled toward the head. Due
to nebulous reasoning involving Planck lengths, you should be able to model the positions of the knots on a
two-dimensional grid. Then, by following a hypothetical series of motions (your puzzle input) for the head, you can
determine how the tail will move. Due to the aforementioned Planck lengths, the rope must be quite short; in fact, the
head (H) and tail (T) must always be touching (diagonally adjacent and even overlapping both count as touching):

....
.TH.
....

....
.H..
..T.
....

...
.H. (H covers T)
...

If the head is ever two steps directly up, down, left, or right from the tail, the tail must also move one step in that
direction so it remains close enough:

.....    .....    .....
.TH.. -> .T.H. -> ..TH.
.....    .....    .....

...    ...    ...
.T.    .T.    ...
.H. -> ... -> .T.
...    .H.    .H.
...    ...    ...

Otherwise, if the head and tail aren't touching and aren't in the same row or column, the tail always moves one step
diagonally to keep up:

.....    .....    .....
.....    ..H..    ..H..
..H.. -> ..... -> ..T..
.T...    .T...    .....
.....    .....    .....

.....    .....    .....
.....    .....    .....
..H.. -> ...H. -> ..TH.
.T...    .T...    .....
.....    .....    .....

You just need to work out where the tail goes as the head follows a series of motions. Assume the head and the tail both
start at the same position, overlapping. For example:

R 4
U 4
L 3
D 1
R 4
D 1
L 5
R 2

This series of motions moves the head right four steps, then up four steps, then left three steps, then down one step,
and so on. After each step, you'll need to update the position of the tail if the step means the head is no longer
adjacent to the tail. Visually, these motions occur as follows (s marks the starting position as a reference point):

== Initial State ==

......
......
......
......
H.....  (H covers T, s)

== R 4 ==

......
......
......
......
TH....  (T covers s)

......
......
......
......
sTH...

......
......
......
......
s.TH..

......
......
......
......
s..TH.

== U 4 ==

......
......
......
....H.
s..T..

......
......
....H.
....T.
s.....

......
....H.
....T.
......
s.....

....H.
....T.
......
......
s.....

== L 3 ==

...H..
....T.
......
......
s.....

..HT..
......
......
......
s.....

.HT...
......
......
......
s.....

== D 1 ==

..T...
.H....
......
......
s.....

== R 4 ==

..T...
..H...
......
......
s.....

..T...
...H..
......
......
s.....

......
...TH.
......
......
s.....

......
....TH
......
......
s.....

== D 1 ==

......
....T.
.....H
......
s.....

== L 5 ==

......
....T.
....H.
......
s.....

......
....T.
...H..
......
s.....

......
......
..HT..
......
s.....

......
......
.HT...
......
s.....

......
......
HT....
......
s.....

== R 2 ==

......
......
.H....  (H covers T)
......
s.....

......
......
.TH...
......
s.....

After simulating the rope, you can count up all of the positions the tail visited at least once. In this diagram, s
again marks the starting position (which the tail also visited) and # marks other positions the tail visited:

..##..
...##.
.####.
....#.
s###..

So, there are 13 positions the tail visited at least once. Simulate your complete hypothetical series of motions. How
many positions does the tail of the rope visit at least once?

*/

type coordinate struct {
	x int
	y int
}

type rope struct {
	head    *coordinate
	tail    *coordinate
	visited map[coordinate]struct{}
}

type direction byte

const (
	Up    direction = 'U'
	Right           = 'R'
	Down            = 'D'
	Left            = 'L'
)

type instruction struct {
	direction direction
	amount    int8
}

func initRope() *rope {
	return &rope{
		head:    &coordinate{0, 0},
		tail:    &coordinate{0, 0},
		visited: map[coordinate]struct{}{coordinate{0, 0}: {}},
	}
}

func (r *rope) move(instruction *instruction) {
	for i := int8(0); i < instruction.amount; i++ {
		r.moveOne(instruction.direction)
	}
}

func (r *rope) moveOne(direction direction) {
	// do the move of the head
	switch direction {
	case Up:
		r.head.y += 1
	case Right:
		r.head.x += 1
	case Down:
		r.head.y -= 1
	case Left:
		r.head.x -= 1
	}

	// do the move of the tail
	r.makeTailFollowHead()
	// store the new position of the tail
	r.visited[*r.tail] = struct{}{}
}

func (r *rope) makeTailFollowHead() {
	if util.AbsInt(r.head.x-r.tail.x) <= 1 && util.AbsInt(r.head.y-r.tail.y) <= 1 {
		// no need to move, we are close enough
		return
	}
	if util.AbsInt(r.head.x-r.tail.x) <= 1 {
		r.tail.x = r.head.x
		if r.tail.y < r.head.y {
			r.tail.y += 1
		} else {
			r.tail.y -= 1
		}
	} else {
		r.tail.y = r.head.y
		if r.tail.x < r.head.x {
			r.tail.x += 1
		} else {
			r.tail.x -= 1
		}
	}
}

func parse(input string) []instruction {
	var instructions []instruction
	sc := bufio.NewScanner(strings.NewReader(input))
	for sc.Scan() {
		tokens := strings.Fields(sc.Text())
		amount, _ := strconv.Atoi(tokens[1])
		instructions = append(
			instructions,
			instruction{
				direction: direction(tokens[0][0]),
				amount:    int8(amount),
			},
		)
	}
	return instructions
}

func doSolution1(raw string) int {
	instructions := parse(raw)
	rope := initRope()

	for _, instruction := range instructions {
		rope.move(&instruction)
	}

	return len(rope.visited)
}

func Solution1() int {
	return doSolution1(util.GetInputContent())
}
